spring:
    dataSource:
      url: jdbc:h2:mem:sdw2023
      username: sdw2023
      password:
    jpa:
      show-sql: true
      open-in-view: false
      hibernate:
        ddl-auto: create #sempre que rodar é recriado as tabelas
      properties:
        hibernate:
          format_sql: true
    h2:
      console:
        enabled: true
        path: /h2-console #acessar o console via navegador
        settings:
          trace: false
          web-allow-others: false
server:
  port: 8090